### ISSUE TITLE
Upgrade Emogrifier to support php 7.4

### ISSUE THREAD

**Issue by natino45** [lekoala/silverstripe-mailgun#1]
Installation failed on php7.4 setup due to the version 2 of Emogrifier not supporting it.

**Comment by lekoala** [comment]
this module should support both emogrifier v2 or v3 in EmailUtils. You should be able to specify v3 in your composer json. If it doesn't work maybe it requires some tweaking of the composer.json but I'm not sure why it wouldn't work

**Comment by natino45** [comment]
I have "pelago/emogrifier": "^3.1" in composer.json  but requiring this packages fails

lekoala/silverstripe-mailgun dev-master requires pelago/emogrifier ^2.0

**Comment by thats4shaw** [comment]
Fix both in https://github.com/coldblooded01/silverstripe-mailgun/commit/0844b930814bb50836e24bc985624fb5e8e88623 and https://github.com/SomarDesignStudios/silverstripe-mailgun/commit/52e5adaf7924055652651bd53c7806e753ed49fa.

**Comment by lekoala** [comment]
fixed in https://github.com/lekoala/silverstripe-mailgun/commit/405e4100ca9bb5c42c2f6a307a43a0486342258c
as well
