### ISSUE TITLE
SilverStripe 5 support

### ISSUE THREAD

**Issue by palomamtnez** [lekoala/silverstripe-mailgun#14]
Are there any plans to make it compatible with SS 5 :) ?

**Comment by lekoala** [comment]
i have to see if my single client using this module is willing to update or not :-)

otherwise, i've got pretty much the idea how to do that since i've made the update for my sparkpost and mandrill module, but currently i have no project using it on ss5

**Comment by palomamtnez** [comment]
Thank you for your response :)!

Yeah it makes sense. 
I needed to finish the setup for emails on my SS5 project,  so I had a read to the way that SS5 handles it now and ended up only installing the symfony-mailgun repo, and only with that, I was able to use Mailgun 🙌 

https://docs.silverstripe.org/en/5/developer_guides/email/
https://github.com/symfony/mailgun-mailer
