### ISSUE TITLE
Drop CMS dependency (framework-only)

### ISSUE THREAD

**Issue by micschk** [lekoala/silverstripe-mailgun#15]
Hi Thomas, does this module actually require the CMS or would just framework suffice? It's currently introduced in a clients' framework-only project by another dev. But in this project it's undesirable to also pull in all the CMS modules. 

On first glance I don't see a reason why CMS should be required(?)

**Comment by lekoala** [comment]
it shouldn't
i don't remember exactly maybe it was just for unit testing reason
at any rate, let's give it a try i had similar requests for my other mailers

https://github.com/lekoala/silverstripe-mailgun/releases/tag/1.2.2
