### ISSUE TITLE
On SS 4.4, the mailgun icon throws error in admin.

### ISSUE THREAD

**Issue by joeyd** [lekoala/silverstripe-mailgun#2]
Error returned is...

[User Notice] File mailgun/images/mailgun-icon.png does not exist
GET /admin/pages/

Line 90 in /vendor/silverstripe/framework/src/Control/SimpleResourceURLGenerator.php

If I comment out line 61 of MailgunAdmin.php, the error goes away.

**Comment by lekoala** [comment]
Yes it's probably a vendor module issue most of the time I leave my modules in my root folder. Probably easy to fix by using the new module path conventions
